# Generated by Django 4.2.6 on 2023-10-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tcc", "0002_alter_programa_indice_alter_programa_modalidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposta",
            name="numero_de_parcelas",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="proposta",
            name="valor_principal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
