# Generated by Django 4.2.6 on 2023-10-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tcc", "0003_proposta_numero_de_parcelas_proposta_valor_principal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aliquota",
            name="aliquota",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Taxa % a.a."
            ),
        ),
        migrations.AlterField(
            model_name="aliquota",
            name="indice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tcc.indice",
                verbose_name="Índice",
            ),
        ),
        migrations.AlterField(
            model_name="aliquota",
            name="vigencia",
            field=models.DateField(verbose_name="Data Inicial de Vigência"),
        ),
        migrations.AlterField(
            model_name="indice",
            name="descricao",
            field=models.CharField(max_length=100, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="modalidade",
            name="descricao",
            field=models.CharField(max_length=100, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="data_pagamento",
            field=models.DateField(verbose_name="Data de Pagamento"),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="numero",
            field=models.IntegerField(verbose_name="Número"),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="vencimento",
            field=models.DateField(verbose_name="Data de Vencimento"),
        ),
        migrations.AlterField(
            model_name="programa",
            name="descricao",
            field=models.CharField(max_length=100, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="programa",
            name="indice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="tcc.indice",
                verbose_name="Índice",
            ),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="data_criacao",
            field=models.DateField(verbose_name="Data de Criação"),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="numero_de_parcelas",
            field=models.IntegerField(default=0, verbose_name="Número de Parcelas"),
        ),
        migrations.AlterField(
            model_name="telefone",
            name="numero",
            field=models.CharField(max_length=9, verbose_name="Número"),
        ),
    ]
