# Generated by Django 4.2.5 on 2023-09-19 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tcc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programa",
            name="indice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="tcc.indice"
            ),
        ),
        migrations.AlterField(
            model_name="programa",
            name="modalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="tcc.modalidade"
            ),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="tcc.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="programa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="tcc.programa"
            ),
        ),
    ]
